### ISSUE TITLE
Loading the plugin fails with NiFi 2.x

### ISSUE THREAD

**Issue by henrikjohansen** [blezek/nifi-dicom#17]
Loading the plugin fails with NiFi 2.0.0-M3  : 

```
2024-06-21 09:20:43,988 ERROR [main] org.apache.nifi.NiFi Failure to launch NiFi
java.lang.NoSuchMethodError: 'org.apache.nifi.components.PropertyDescriptor$Builder org.apache.nifi.components.PropertyDescriptor$Builder.expressionLanguageSupported(boolean)'
	at com.blezek.nifi.dicom.DeidentificationController.<clinit>(DeidentificationController.java:45)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at org.apache.nifi.nar.StandardExtensionDiscoveringManager.getClass(StandardExtensionDiscoveringManager.java:452)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.lookupControllerServiceImpls(HtmlDocumentationWriter.java:764)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.writeValidValues(HtmlDocumentationWriter.java:708)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.writeProperties(HtmlDocumentationWriter.java:405)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.writeProperties(HtmlDocumentationWriter.java:66)
	at org.apache.nifi.documentation.html.AbstractHtmlDocumentationWriter.writeBody(AbstractHtmlDocumentationWriter.java:115)
	at org.apache.nifi.documentation.html.AbstractHtmlDocumentationWriter.write(AbstractHtmlDocumentationWriter.java:65)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.write(HtmlDocumentationWriter.java:66)
	at org.apache.nifi.documentation.DocGenerator.document(DocGenerator.java:157)
	at org.apache.nifi.documentation.DocGenerator.documentConfigurableComponent(DocGenerator.java:120)
	at org.apache.nifi.documentation.DocGenerator.generate(DocGenerator.java:66)
	at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:833)
	at org.apache.nifi.NiFi.<init>(NiFi.java:172)
	at org.apache.nifi.NiFi.<init>(NiFi.java:83)
	at org.apache.nifi.NiFi.main(NiFi.java:332)
2024-06-21 09:21:01,062 INFO [Checkpoint FlowFile Repository] o.a.n.c.r.WriteAheadFlowFileRepository Initiating checkpoint of FlowFile Repository
```

**Comment by Tallens** [comment]
Same issue with NIFI 2.0.0-M4, so next version didn't solve it, which indicates that this might be a Nifi-dicom issue.

...is there a forked update for this?

Best.
T

**Comment by henrikjohansen** [comment]
@Tallens Essentially the nifi-dicom plugin needs to be compiled against NiFi 2.x before it will work.  Anyone undertaking this should probably also update the dcm4che and pixelmed dependencies as the plugin targets some rather old versions IIRC.

I have a WIP implementation of a new DICOM processor in Python for NiFi 2.x which implements most of nifi-dicom's functionality and also adds support for Query/Retrieve operations which may be open sourced at some point in the future.

**Comment by Tallens** [comment]
I'd be most interested in such a implimentation.

I have tried to recompile a few fixes of his original code, to fix the issue and so far have only have mild success in doing so, looks mostly like it's a slight chance in how some of the main functions work between 1.4 and 2.0+

Cheers.

**Comment by blezek** [comment]
Hi all,  I just jumped back into this code (sorry, GitHub has not been sending notification emails about these issues).  I'm looking to update to NiFi 1.27.0 and 2.0.0-M4.  Stay tuned.
-dan

**Comment by Tallens** [comment]
Hi Blezek, this is good news, and welcome back, I'll be looking forward unto hearing what conclusion you reach on this.

**Comment by blezek** [comment]
@henrikjohansen if you are still interested, please try the `2.0.0-M4` release of `nifi-dicom`.

**Comment by henrikjohansen** [comment]
@blezek I just tried `nifi-dicom` v1.27.0 and v1.27.1 against NiFi 1.27 and 1.28 - both failed when loading the NAR with the error below.

I will try the 2.x version shortly ....

```
2024-10-30 21:01:25,524 ERROR [main] org.apache.nifi.NiFi Failure to launch NiFi
java.lang.UnsupportedClassVersionError: com/blezek/nifi/dicom/DeidentificationController has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.apache.nifi.nar.StandardExtensionDiscoveringManager.getClass(StandardExtensionDiscoveringManager.java:336)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.lookupControllerServiceImpls(HtmlDocumentationWriter.java:952)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.writeValidValues(HtmlDocumentationWriter.java:830)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.writeProperties(HtmlDocumentationWriter.java:507)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.writeBody(HtmlDocumentationWriter.java:163)
	at org.apache.nifi.documentation.html.HtmlDocumentationWriter.write(HtmlDocumentationWriter.java:95)
	at org.apache.nifi.documentation.DocGenerator.document(DocGenerator.java:140)
	at org.apache.nifi.documentation.DocGenerator.documentConfigurableComponent(DocGenerator.java:105)
	at org.apache.nifi.documentation.DocGenerator.generate(DocGenerator.java:63)
	at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:790)
	at org.apache.nifi.NiFi.<init>(NiFi.java:172)
	at org.apache.nifi.NiFi.<init>(NiFi.java:83)
	at org.apache.nifi.NiFi.main(NiFi.java:332)
```

**Comment by blezek** [comment]
> @blezek I just tried `nifi-dicom` v1.27.0 and v1.27.1 against NiFi 1.27 and 1.28 - both failed when loading the NAR with the error below. Looks like Java 21 is a bit too much for NiFi 1.x versions ?
> 
> I will try the 2.x version shortly ....
> 
> ```
> 2024-10-30 21:01:25,524 ERROR [main] org.apache.nifi.NiFi Failure to launch NiFi
> java.lang.UnsupportedClassVersionError: com/blezek/nifi/dicom/DeidentificationController has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 55.0

Fixed this by making the ClassFiles compatible with Java 8.  Try the 1.27.2 release.  It's working for me.

**Comment by henrikjohansen** [comment]
> Fixed this by making the ClassFiles compatible with Java 8. Try the 1.27.2 release. It's working for me.

@blezek I can confirm that `v1.27.2` works :+1:
